modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/onebeastchris/Hurricane-Modded/issues"
[[mods]]
modId="$id"
version="$version"
displayName="$name"
displayURL="$url"
logoFile= "../assets/floodgate/icon.png"
authors="$author"
description="$description"
[[mixins]]
config = "hurricane.mixins.json"
[[dependencies.hurricane]]
modId="neoforge"
type="required"
versionRange="[21.0.0-beta,)"
ordering="NONE"
side="BOTH"
[[dependencies.hurricane]]
modId="minecraft"
type="required"
versionRange="[$minecraft_version,)"
ordering="NONE"
side="BOTH"
[[dependencies.hurricane]]
modId="floodgate"
type="optional"
ordering="AFTER"
versionRange="[2.2.3-SNAPSHOT,)"
side="BOTH"
[[dependencies.hurricane]]
modId="geyser_neoforge"
versionRange="[2.3.2-SNAPSHOT,)"
type="optional"
ordering="AFTER"
side="BOTH"